//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountBuddy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppConnectionHeader
    {
        public long Id { get; set; }
        public Nullable<long> AppConnectionId { get; set; }
        public string HKey { get; set; }
        public string HValue { get; set; }
    
        public virtual AppConnection AppConnection { get; set; }
    }
}
