//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountBuddy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppConnectionLoginSystem
    {
        public long Id { get; set; }
        public Nullable<long> AppConnectionId { get; set; }
        public Nullable<int> AppMasterId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> LoginAt { get; set; }
        public string Computername { get; set; }
        public string Username { get; set; }
        public string UserDomainName { get; set; }
    
        public virtual AppConnection AppConnection { get; set; }
        public virtual AppMaster AppMaster { get; set; }
    }
}
