//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountBuddy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppConnection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppConnection()
        {
            this.AppConnectionHeaders = new HashSet<AppConnectionHeader>();
            this.AppConnectionLoginFaileds = new HashSet<AppConnectionLoginFailed>();
            this.AppConnectionLoginSucceeds = new HashSet<AppConnectionLoginSucceed>();
            this.AppConnectionReConnecteds = new HashSet<AppConnectionReConnected>();
            this.AppConnectionLoginWebAdmins = new HashSet<AppConnectionLoginWebAdmin>();
            this.AppConnectionLoginSystems = new HashSet<AppConnectionLoginSystem>();
        }
    
        public long Id { get; set; }
        public string ConnectionId { get; set; }
        public Nullable<System.DateTime> ConnectedAt { get; set; }
        public Nullable<System.DateTime> DisconnectedAt { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppConnectionHeader> AppConnectionHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppConnectionLoginFailed> AppConnectionLoginFaileds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppConnectionLoginSucceed> AppConnectionLoginSucceeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppConnectionReConnected> AppConnectionReConnecteds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppConnectionLoginWebAdmin> AppConnectionLoginWebAdmins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppConnectionLoginSystem> AppConnectionLoginSystems { get; set; }
    }
}
