//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountBuddy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyFile
    {
        public int Id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string AttchmentCode { get; set; }
        public byte[] Image { get; set; }
    
        public virtual CompanyDetail CompanyDetail { get; set; }
    }
}
