//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountBuddy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomFormat
    {
        public int Id { get; set; }
        public string CurrencySymbol { get; set; }
        public string CurrencyName1 { get; set; }
        public Nullable<bool> IsPrefix { get; set; }
        public Nullable<bool> IsSuffix { get; set; }
        public string CurrencyName2 { get; set; }
        public string DateFormat { get; set; }
        public string NumberFormat { get; set; }
        public Nullable<int> CompanyId { get; set; }
    
        public virtual CompanyDetail CompanyDetail { get; set; }
    }
}
