//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountBuddy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Tax_Detail
    {
        public long Id { get; set; }
        public long PD_ID { get; set; }
        public int TaxId { get; set; }
        public decimal TaxPercentage { get; set; }
        public decimal TaxAmount { get; set; }
    
        public virtual Ledger Ledger { get; set; }
        public virtual PaymentDetail PaymentDetail { get; set; }
    }
}
