//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountBuddy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> StockGroupId { get; set; }
        public Nullable<int> UOMId { get; set; }
        public Nullable<decimal> PurchaseRate { get; set; }
        public Nullable<decimal> SellingRate { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<double> GST { get; set; }
        public Nullable<double> OpeningStock { get; set; }
        public Nullable<double> ReOrderLevel { get; set; }
        public byte[] ProductImage { get; set; }
    
        public virtual StockGroup StockGroup { get; set; }
        public virtual UOM UOM { get; set; }
    }
}
