//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountBuddy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Spec_Process_Detail
    {
        public int Id { get; set; }
        public long PSId { get; set; }
        public int ProductId { get; set; }
        public int Qty { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Product_Spec_Process Product_Spec_Process { get; set; }
    }
}
