//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountBuddy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Spec_Detail
    {
        public long Id { get; set; }
        public Nullable<long> Product_Spec_Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Qty { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Product_Spec_Master Product_Spec_Master { get; set; }
    }
}
