//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountBuddy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRequestStatusDetail
    {
        public int Id { get; set; }
        public Nullable<long> PRId { get; set; }
        public Nullable<int> RequestBy { get; set; }
        public Nullable<System.DateTime> RequestAt { get; set; }
        public Nullable<int> RequestTo { get; set; }
        public Nullable<System.DateTime> ResponseAt { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
    
        public virtual PurchaseRequest PurchaseRequest { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
    }
}
