//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountBuddy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Order_TaxDetail
    {
        public long Id { get; set; }
        public Nullable<long> SO_ID { get; set; }
        public Nullable<int> TaxId { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
    
        public virtual SalesOrder SalesOrder { get; set; }
        public virtual TaxMaster TaxMaster { get; set; }
    }
}
