//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountBuddy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaxMaster()
        {
            this.Receipt_Tax_Detail = new HashSet<Receipt_Tax_Detail>();
            this.Purchase_Order_TaxDetail = new HashSet<Purchase_Order_TaxDetail>();
            this.Sales_Order_TaxDetail = new HashSet<Sales_Order_TaxDetail>();
        }
    
        public int Id { get; set; }
        public int LedgerId { get; set; }
        public decimal TaxPercentage { get; set; }
        public bool Status { get; set; }
    
        public virtual Ledger Ledger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt_Tax_Detail> Receipt_Tax_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Order_TaxDetail> Purchase_Order_TaxDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Order_TaxDetail> Sales_Order_TaxDetail { get; set; }
    }
}
